### ISSUE TITLE
The new discovery algorithm is producing a strange exception

### ISSUE THREAD

**Issue by niau** [iTransformers/netTransformer#31]
05-31@16:33:32    - ianaifType
05-31@16:33:32    - ianaifType
05-31@16:33:32    - ianaifType
05-31@16:33:32    - ianaifType
05-31@16:34:05    - ianaifType
Exception in thread "main" java.lang.NullPointerException
05-31@16:34:05    - ianaifType
05-31@16:34:05    - ianaifType
05-31@16:34:05    - ianaifType
05-31@16:34:05    - ianaifType
05-31@16:34:05    - ianaifType
05-31@16:34:05    - ianaifType
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
05-31@16:34:05    - ianaifType
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
05-31@16:34:05    - ianaifType
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
05-31@16:34:05    - ianaifType
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2613)
	at net.itransformers.idiscover.v2.core.parallel.ParallelNetworkNodeDiscovererImpl.discoverNetwork(ParallelNetworkNodeDiscovererImpl.java:49)
	at net.itransformers.idiscover.v2.core.Main.main(Main.java:75)
05-31@16:34:05    - ianaifType
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05-31@16:34:05    - ianaifType
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
05-31@16:34:05    - ianaifType
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
05-31@16:34:05    - ianaifType
Caused by: java.lang.NullPointerException
05-31@16:34:05    - ianaifType
05-31@16:34:05    - ianaifType
05-31@16:34:05    - ianaifType
05-31@16:34:05    - ianaifType
05-31@16:34:05    - ianaifType
05-31@16:34:05    - ianaifType
05-31@16:34:05    - ianaifType
05-31@16:34:05    - ianaifType
05-31@16:34:05    - ianaifType
05-31@16:34:05    - ianaifType
[B@7add5317
	at net.itransformers.idiscover.v2.core.NetworkNodeDiscoverer.fireNeighboursDiscoveredEvent(NetworkNodeDiscoverer.java:123)
05-31@16:34:06    - Device has an invalid ipAddreess DeviceNeighbour{hostName='7k-1', neighbourIpAddress='', known=false}
	at net.itransformers.idiscover.v2.core.NetworkNodeDiscoverer.handleNodeDiscoveredOrNotDiscoveredEvent(NetworkNodeDiscoverer.java:114)
05-31@16:34:06    - New node is discovered, nodeId=core0-vdc1-core0-vdc2
	at net.itransformers.idiscover.v2.core.NetworkNodeDiscoverer.fireNodeDiscoveredEvent(NetworkNodeDiscoverer.java:97)
	at net.itransformers.idiscover.v2.core.parallel.DiscoveryWorker.compute(DiscoveryWorker.java:62)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:843)
	at net.itransformers.idiscover.v2.core.parallel.DiscoveryWorker.compute(DiscoveryWorker.java:75)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by niau** [comment]
@vasil-yordanov  please have a look

**Comment by niau** [comment]
I believe that this might be caused by a neighbor being discovered for whom we don't know the ipAddress but just the name or the mac address.
